Section 1 of:

https://www.udemy.com/deep-learning-prerequisites-the-numpy-stack-in-python/

https://deeplearningcourses.com/c/deep-learning-prerequisites-the-numpy-stack-in-python

## Arrays vs Lists

In [1]:
import numpy as np

In [2]:
L = [1,2,3]

In [3]:
A = np.array([1,2,3])

In [4]:
for e in L:
  print(e)

1
2
3


In [5]:
for e in A:
  print(e)

1
2
3


In [6]:
L.append(4)

In [7]:
L

[1, 2, 3, 4]

In [8]:
A.append(4) # doesn't work

AttributeError: ignored

In [9]:
L + [5]

[1, 2, 3, 4, 5]

In [10]:
A + np.array([4])

array([5, 6, 7])

In [11]:
A + np.array([4,5,6])

array([5, 7, 9])

In [12]:
A + np.array([4,5]) # doesn't work

ValueError: ignored

In [13]:
2 * A

array([2, 4, 6])

In [14]:
2 * L

[1, 2, 3, 4, 1, 2, 3, 4]

In [15]:
L + L

[1, 2, 3, 4, 1, 2, 3, 4]

In [16]:
L2 = []
for e in L:
  L2.append(e + 3)

In [17]:
L2

[4, 5, 6, 7]

In [18]:
L2 = [e + 3 for e in L]

In [19]:
L2

[4, 5, 6, 7]

In [20]:
L2 = []
for e in L:
  L2.append(e**2)

In [21]:
L2

[1, 4, 9, 16]

In [22]:
A**2

array([1, 4, 9])

In [23]:
np.sqrt(A)

array([1.        , 1.41421356, 1.73205081])

In [24]:
np.log(A)

array([0.        , 0.69314718, 1.09861229])

In [25]:
np.exp(A)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [26]:
np.tanh(A)

array([0.76159416, 0.96402758, 0.99505475])

## The Dot Product

$$ a \cdot b = a^T b = \sum_{d=1}^D a_d b_d $$

In [27]:
a = np.array([1,2])
b = np.array([3,4])

In [28]:
dot = 0
for e, f in zip(a, b):
  dot += e*f
dot

11

In [29]:
# use integer index
dot = 0
for i in range(len(a)):
  dot += a[i] * b[i]
dot

11

In [30]:
a * b

array([3, 8])

In [31]:
np.sum(a * b)

11

In [32]:
(a * b).sum()

11

In [33]:
np.dot(a, b)

11

In [34]:
a.dot(b)

11

In [35]:
b.dot(a)

11

In [36]:
a @ b

11

$$ a^T b = \left\lVert a \right\rVert \left\lVert b \right\rVert \cos \theta_{ab}$$

$$ \cos \theta_{ab} = \frac{a^T b}{\left\lVert a \right\rVert \left\lVert b \right\rVert} $$

$$ \left\lVert a \right\rVert = \sqrt{\sum_{d=1}^D a_d^2 } $$

In [37]:
amag = np.sqrt((a * a).sum())
amag

2.23606797749979

In [38]:
amag = np.linalg.norm(amag)
amag

2.23606797749979

In [39]:
cosangle = a.dot(b) / (np.linalg.norm(a) * np.linalg.norm(b))

In [40]:
cosangle

0.9838699100999074

In [41]:
angle = np.arccos(cosangle)
angle

0.17985349979247847

## Speed Test

In [43]:
## speed comparison ##
import numpy as np
from datetime import datetime

# note: you can also use %timeit

a = np.random.randn(100)
b = np.random.randn(100)
T = 100000

def slow_dot_product(a, b):
  result = 0
  for e, f in zip(a, b):
    result += e*f
  return result

t0 = datetime.now()
for t in range(T):
  slow_dot_product(a, b)
dt1 = datetime.now() - t0

t0 = datetime.now()
for t in range(T):
  a.dot(b)
dt2 = datetime.now() - t0

print("dt1 / dt2:", dt1.total_seconds() / dt2.total_seconds())

dt1 / dt2: 64.64661497125196


## Matrices

In [44]:
L = [[1,2], [3,4]]
L

[[1, 2], [3, 4]]

In [45]:
L[0]

[1, 2]

In [46]:
L[0][1]

2

In [47]:
A = np.array([[1,2], [3,4]])
A

array([[1, 2],
       [3, 4]])

In [48]:
A[0][1]

2

In [49]:
A[0,1]

2

In [50]:
A[:,0]

array([1, 3])

In [51]:
A.T

array([[1, 3],
       [2, 4]])

In [52]:
np.exp(A)

array([[ 2.71828183,  7.3890561 ],
       [20.08553692, 54.59815003]])

In [53]:
np.exp(L)

array([[ 2.71828183,  7.3890561 ],
       [20.08553692, 54.59815003]])

In [54]:
B = np.array([[1,2,3],[4,5,6]])
B

array([[1, 2, 3],
       [4, 5, 6]])

In [55]:
A.dot(B)

array([[ 9, 12, 15],
       [19, 26, 33]])

In [56]:
# error! inner dimensions must match
A.dot(B.T)

ValueError: ignored

In [57]:
np.linalg.det(A)

-2.0000000000000004

In [58]:
np.linalg.inv(A)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [59]:
np.linalg.inv(A).dot(A)

array([[1.00000000e+00, 0.00000000e+00],
       [1.11022302e-16, 1.00000000e+00]])

In [60]:
np.trace(A)

5

In [61]:
np.diag(A)

array([1, 4])

In [63]:
np.diag([1, 4])

array([[1, 0],
       [0, 4]])

In [64]:
np.linalg.eig(A)

(array([-0.37228132,  5.37228132]), array([[-0.82456484, -0.41597356],
        [ 0.56576746, -0.90937671]]))

In [65]:
Lam, V = np.linalg.eig(A)

In [66]:
V[:,0] * Lam[0] == A @ V[:,0]

array([ True, False])

In [67]:
V[:,0] * Lam[0], A @ V[:,0]

(array([ 0.30697009, -0.21062466]), array([ 0.30697009, -0.21062466]))

In [68]:
np.allclose(V[:,0] * Lam[0], A @ V[:,0])

True

In [69]:
np.allclose(V @ np.diag(Lam), A @ V)

True

## Solving Linear Systems

In [70]:
A = np.array([[1, 1], [1.5, 4]])
b = np.array([2200, 5050])

In [71]:
np.linalg.solve(A, b)

array([1500.,  700.])

In [72]:
# don't do this
np.linalg.inv(A).dot(b)

array([1500.,  700.])

## Generating Data

In [73]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [74]:
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [75]:
10 * np.ones((2, 3))

array([[10., 10., 10.],
       [10., 10., 10.]])

In [76]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [77]:
np.random.random()

0.5637169392935921

In [78]:
np.random.random((2, 3))

array([[0.77744274, 0.21503157, 0.29160993],
       [0.04266343, 0.69753803, 0.76455997]])

In [79]:
np.random.randn(2, 3)

array([[ 0.1016958 ,  0.31418748,  0.64829256],
       [ 1.9339179 ,  0.9006282 , -0.52569577]])

In [80]:
R = np.random.randn(10000)

In [81]:
R.mean()

0.010137546072198363

In [82]:
np.mean(R)

0.010137546072198363

In [83]:
R.var()

0.9932437472024359

In [84]:
R = np.random.randn(10000, 3)

In [85]:
R.mean(axis=0)

array([ 0.01054297, -0.0044528 , -0.00481728])

In [86]:
R.mean(axis=1).shape

(10000,)

In [87]:
np.cov(R).shape

(10000, 10000)

In [88]:
np.cov(R.T)

array([[ 0.98735245, -0.00920079,  0.00300037],
       [-0.00920079,  0.99625989, -0.00402462],
       [ 0.00300037, -0.00402462,  1.00052687]])

In [89]:
np.cov(R, rowvar=False)

array([[ 0.98735245, -0.00920079,  0.00300037],
       [-0.00920079,  0.99625989, -0.00402462],
       [ 0.00300037, -0.00402462,  1.00052687]])

In [90]:
np.random.randint(0, 10, size=(3, 3))

array([[3, 5, 0],
       [8, 8, 6],
       [9, 0, 7]])

In [91]:
np.random.choice(10, size=(3, 3))

array([[8, 9, 4],
       [3, 8, 1],
       [7, 4, 5]])